from django.urls import include, path
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from . import views

router = DefaultRouter()
router.register(r"users", views.UserViewSet, basename="user")
router.register(r"projects", views.ProjectViewSet, basename="project")
router.register(r"time-entries", views.TimeEntryViewSet, basename="time-entry")
router.register(r"time-tracks", views.TimeTrackViewSet, basename="timetrack")
router.register(r"summary", views.SummaryViewSet, basename="summary")
router.register(r"data", views.DataPortabilityViewSet, basename="data")
router.register(r"sync", views.SyncViewSet, basename="sync")

urlpatterns = [
    # JWT Authentication endpoints for obtaining and refreshing tokens.
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    # Include all the URLs generated by the router under the root path.
    path("", include(router.urls)),
]
